### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by zupo**
Only need to run this once, not on every release.

### CODE REVIEW

**Comment by zupo** [comment]
Ah no, since we don't take a subset of production DB, the review app DB is empty and hence needs this installed. 

Can't we put this into an alembic step instead?

**Comment by zupo** [comment]
> Can't we put this into an alembic step instead?

Also no:

```
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.InsufficientPrivilege) permission denied to create extension "pgcrypto"
HINT:  Must be superuser to create this extension.
```

So for now, I'm leaving it as is. Not ideal but I have other battles to fight.

**Comment by sayanarijit** [comment]
I think we can use the kai trick.

```
if [ "$REVIEWAPP" ]; then create extension; fi
```

**Comment by zupo** [comment]
It will still run on subsequent deploys of the review app. So meh.

**Pull request closed without merging**
