### PR TITLE
Add flake8-lineleak

### PR DESCRIPTION
**Pull request by ayivima**

### CODE REVIEW

**Comment by zupo** [comment]
The testing build failed: https://travis-ci.com/niteoweb/pyramid-realworld-example-app/builds/114484713

You forgot to commit the change to Pipfile.lock.

**Comment by ayivima** [comment]
> The testing build failed: https://travis-ci.com/niteoweb/pyramid-realworld-example-app/builds/114484713
> 
> You forgot to commit the change to Pipfile.lock.

I am doing that right away.

**Comment by bertjwregeer** [comment]
I appreciate you working on this, but are you aware that you are able to push new changes to an existing branch and it will automatically update the existing PR? This way you don't have to create a new PR for each small change/attempt.

This will also make it easier for us to review the changes, and provide feedback without having to refer to the now many closed PR's.

#45 #46 #47 #49 #50 #48

**Comment by ayivima** [comment]
Surely. That's well taken. Pardon my struggles :)

**Comment by zupo** [comment]
Was there any further work done on this? Can I help in some way?

**Comment by ayivima** [comment]
A user of flake8-lineleak reported that this was probably a problem with the flake8 `jobs`. The exception wasn't thrown if he set `jobs=1` in the flake8 config. A link to a discussion on this issue here: https://gitlab.com/pycqa/flake8/issues/164.

**Comment by ayivima** [comment]
This is a post by Ian Stapleton Cordasco on the issue posted above.

> So my hunch was vaguely correct. Your setup.py requires flake8 for setup and is installing it into .eggs. If you pip install flake8 first, clear out your .eggs directory and then run python setup.py flake8 it will just work.
> A temporary solution would be to install flake8 in travis and run your tests like this. I'm going to have to figure out why the egg version of flake8 doesn't work though (and that may take a while).

**Comment by zupo** [comment]
Closing due to inactivity. Please reopen if you want to continue working on this!

**Pull request closed without merging**
